services:
  grafana:
    image: grafana.grafana:latest
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"

  alloy:
    image: grafana/alloy:latest
    ports:
      - "12345:12345"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    ports:
      - "8080:8080"